"""Tests for manifest read/write."""

from __future__ import annotations

import json
from pathlib import Path

from reinicorn.manifest import (
    MANAGED_ASSETS,
    read_manifest,
    sha256_file,
    write_manifest,
)


def test_agents_is_not_a_managed_asset() -> None:
    assert "AGENTS.md" not in MANAGED_ASSETS


def test_editor_hooks_are_managed() -> None:
    """Editor hooks live under .reinicorn/hooks and must be tracked so
    'rcorn update' can sync them and protect local modifications."""
    assert ".reinicorn/hooks" in MANAGED_ASSETS


def test_write_manifest_tracks_editor_hooks(tmp_path: Path):
    """Files under .reinicorn/hooks are recorded in the manifest."""
    repo = tmp_path / "repo"
    hooks = repo / ".reinicorn" / "hooks"
    hooks.mkdir(parents=True)
    (hooks / "block-raw-kb-git.sh").write_text("#!/bin/sh\n")

    write_manifest(repo, version="0.1.0")

    data = json.loads((repo / ".reinicorn" / "manifest.json").read_text())
    assert ".reinicorn/hooks/block-raw-kb-git.sh" in data["files"]


def test_write_manifest_creates_file(tmp_path: Path):
    """write_manifest creates .reinicorn/manifest.json with checksums."""
    repo = tmp_path / "repo"
    repo.mkdir()
    skills = repo / ".agents" / "skills" / "brainstorming"
    skills.mkdir(parents=True)
    (skills / "SKILL.md").write_text("# Brainstorming\n")
    (repo / "AGENTS.md").write_text("# Agents\n")

    write_manifest(repo, version="0.1.0")

    manifest_path = repo / ".reinicorn" / "manifest.json"
    assert manifest_path.is_file()
    data = json.loads(manifest_path.read_text())
    assert data["reinicorn_version"] == "0.1.0"
    assert "installed_at" in data
    assert ".agents/skills/brainstorming/SKILL.md" in data["files"]
    assert "AGENTS.md" not in data["files"]


def test_write_manifest_excludes_lock_owned_files(tmp_path: Path):
    """Files whose skills-dir-relative path is recorded in the skillset
    lock are adapter-managed (owned by `rcorn skills`, not `rcorn update`)
    and must not appear in the manifest, while a native (non-lock-owned)
    file in the same skills dir still does."""
    from reinicorn.skillset.lockfile import SkillsetLock, write_lock

    repo = tmp_path / "repo"
    skills = repo / ".agents" / "skills"
    adapter_skill = skills / "brainstorming"
    adapter_skill.mkdir(parents=True)
    (adapter_skill / "SKILL.md").write_text("# adapter-installed\n")
    native_skill = skills / "using-reinicorn"
    native_skill.mkdir(parents=True)
    (native_skill / "SKILL.md").write_text("# native\n")

    write_lock(
        repo,
        SkillsetLock(
            adapter="superpowers",
            repo="obra/superpowers",
            commit="a" * 40,
            archive_sha256="b" * 64,
            files={"brainstorming/SKILL.md": "irrelevant-hash"},
            wiring={},
        ),
    )

    write_manifest(repo, version="0.1.0")

    data = json.loads((repo / ".reinicorn" / "manifest.json").read_text())
    assert ".agents/skills/brainstorming/SKILL.md" not in data["files"]
    assert ".agents/skills/using-reinicorn/SKILL.md" in data["files"]


def test_collect_files_excludes_generated_wiring_doc(tmp_path: Path) -> None:
    """The skillset wiring doc is generated by `rcorn update`/`rcorn
    skills` (rendered from the doc-type registry), not shipped in the
    package. It sits under `.agents/skills` (a MANAGED_ASSETS dir) and is
    not lock-owned (using-reinicorn is native), so without an explicit
    exclusion `_collect_files` would record it and `rcorn update`'s
    'Removed upstream' check would falsely flag it every run. A native
    skill file in the same skills dir must still be collected."""
    from reinicorn.manifest import _collect_files
    from reinicorn.skillset.wiring import wiring_doc_path

    repo = tmp_path / "repo"
    native_skill = repo / ".agents" / "skills" / "brainstorming"
    native_skill.mkdir(parents=True)
    (native_skill / "SKILL.md").write_text("# native\n")

    wiring_path = wiring_doc_path(repo)
    wiring_path.parent.mkdir(parents=True, exist_ok=True)
    wiring_path.write_text("# Skillset Wiring\n")

    files = _collect_files(repo)

    assert ".agents/skills/brainstorming/SKILL.md" in files
    assert wiring_path.relative_to(repo).as_posix() not in files


def test_collect_files_honours_configured_skills_dir(tmp_path: Path) -> None:
    """Native-skill collection is the DESTINATION half of the configurable
    skills-dir contract: with REINICORN_SKILLS_DIR set to a non-default
    relative dir, `_collect_files` must collect native skills from there,
    not from the hardcoded `.agents/skills`."""
    from reinicorn.manifest import _collect_files

    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / ".reinicorn-config").write_text("REINICORN_SKILLS_DIR=custom/skills\n")
    native_skill = repo / "custom" / "skills" / "brainstorming"
    native_skill.mkdir(parents=True)
    (native_skill / "SKILL.md").write_text("# native\n")

    files = _collect_files(repo)

    assert "custom/skills/brainstorming/SKILL.md" in files
    assert ".agents/skills/brainstorming/SKILL.md" not in files


def test_collect_files_tolerates_an_absolute_skills_dir_outside_the_repo(
    tmp_path: Path,
) -> None:
    """An absolute REINICORN_SKILLS_DIR puts both the skills tree and the
    generated wiring doc outside repo_root. Manifest generation must not
    crash — it simply has nothing to collect or exclude for that dir."""
    outside = tmp_path / "outside-skills"
    outside.mkdir()
    (outside / "brainstorming").mkdir()
    (outside / "brainstorming" / "SKILL.md").write_text("# native\n")

    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / ".reinicorn-config").write_text(f"REINICORN_SKILLS_DIR={outside}\n")
    (repo / ".reinicorn" / "hooks").mkdir(parents=True)
    (repo / ".reinicorn" / "hooks" / "hook.sh").write_text("#!/bin/sh\n")

    data = json.loads(write_manifest(repo, version="0.1.0").read_text())

    hook_hash = sha256_file(repo / ".reinicorn" / "hooks" / "hook.sh")
    assert data["files"] == {".reinicorn/hooks/hook.sh": {"sha256": hook_hash}}


def test_write_manifest_with_no_lock_excludes_nothing(tmp_path: Path):
    """No lockfile present (no adapter installed) means no exclusions —
    lock-owned skipping must tolerate the lock's absence."""
    repo = tmp_path / "repo"
    skills = repo / ".agents" / "skills" / "brainstorming"
    skills.mkdir(parents=True)
    (skills / "SKILL.md").write_text("# some skill\n")

    write_manifest(repo, version="0.1.0")

    data = json.loads((repo / ".reinicorn" / "manifest.json").read_text())
    assert ".agents/skills/brainstorming/SKILL.md" in data["files"]


def test_read_manifest_returns_data(tmp_path: Path):
    """read_manifest returns parsed manifest data."""
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "AGENTS.md").write_text("# Agents\n")
    write_manifest(repo, version="0.1.0")

    data = read_manifest(repo)
    assert data is not None
    assert data["reinicorn_version"] == "0.1.0"
    assert "AGENTS.md" not in data["files"]


def test_read_manifest_returns_none_when_missing(tmp_path: Path):
    """read_manifest returns None when no manifest exists."""
    data = read_manifest(tmp_path)
    assert data is None


def test_read_manifest_returns_none_for_invalid_json(tmp_path: Path):
    """read_manifest returns None when manifest is corrupted."""
    manifest_dir = tmp_path / ".reinicorn"
    manifest_dir.mkdir()
    (manifest_dir / "manifest.json").write_text("not json")
    data = read_manifest(tmp_path)
    assert data is None


def test_read_manifest_returns_none_for_missing_keys(tmp_path: Path):
    """read_manifest returns None when required keys are missing."""
    manifest_dir = tmp_path / ".reinicorn"
    manifest_dir.mkdir()
    (manifest_dir / "manifest.json").write_text('{"foo": "bar"}')
    data = read_manifest(tmp_path)
    assert data is None
