"""Registry-driven skillset wiring doc: creation commands and skill hints."""

from __future__ import annotations

from typing import TYPE_CHECKING

from reinicorn.config import skills_dir
from reinicorn.doc_types import REGISTRY, TitleSource
from reinicorn.skillset.adapter import AdapterError

if TYPE_CHECKING:
    from pathlib import Path

    from reinicorn.doc_types import DocType
    from reinicorn.skillset.adapter import WiringEntry

_WIRING_DOC_PARTS = ("using-reinicorn", "references", "skillset-wiring.md")

_HEADER = (
    "# Skillset Wiring\n"
    "\n"
    "Generated by rcorn — do not edit. Regenerated by `rcorn update` and "
    "`rcorn skills`.\n"
    "\n"
    "| Doc type | Create with | Invoke first |\n"
    "|---|---|---|\n"
)


def render_wiring(wiring: dict[str, WiringEntry] | None) -> tuple[str, list[str]]:
    """Render the skillset wiring table: one row per `REGISTRY` doc type.

    `REGISTRY` is the row source — *wiring* only fills in the "Invoke
    first" column, it never adds rows. A *wiring* key present in
    `REGISTRY` renders its skills, comma-space-joined; a key absent from
    `REGISTRY` is skipped (and reported in the returned list) when its
    entry is `optional`, and otherwise raises `AdapterError` naming the
    unknown key and listing `REGISTRY`'s actual keys.

    Returns `(markdown, skipped_optional_keys)`.
    """
    active: dict[str, WiringEntry] = {}
    skipped: list[str] = []
    for key, entry in (wiring or {}).items():
        if key in REGISTRY:
            active[key] = entry
            continue
        if entry.optional:
            skipped.append(key)
            continue
        raise AdapterError(
            f"Wiring key '{key}' is not a registered doc type.\n"
            f"  Registered doc types: {sorted(REGISTRY)}.\n"
            f"  How to fix: fix the typo in the adapter's wiring block, or "
            f"mark this entry 'optional: true' if '{key}' is expected to be "
            f"absent from this repo's registry."
        )

    rows = [
        f"| {dt.key} | {_create_command(dt)} | {_skills_cell(active.get(dt.key))} |"
        for dt in REGISTRY.values()
    ]
    return _HEADER + "\n".join(rows) + "\n", skipped


def write_wiring(repo_root: Path, wiring: dict[str, WiringEntry] | None) -> Path:
    """Render and write `<skills_dir>/using-reinicorn/references/skillset-wiring.md`."""
    markdown, _skipped = render_wiring(wiring)
    out_path = (repo_root / skills_dir(repo_root)).joinpath(*_WIRING_DOC_PARTS)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(markdown)
    return out_path


def _create_command(dt: DocType) -> str:
    """The `rcorn <key> <verb> ...` cell, shaped by the type's title source."""
    if dt.title_source is TitleSource.TITLE:
        return f'`rcorn {dt.key} {dt.create_verb} "<title>"`'
    if dt.title_source is TitleSource.FREE_TEXT:
        return f'`rcorn {dt.key} {dt.create_verb} "<text>"`'
    return f"`rcorn {dt.key} {dt.create_verb}`"


def _skills_cell(entry: WiringEntry | None) -> str:
    """Comma-space-joined skill names, or an em dash when unwired."""
    if entry is None:
        return "—"
    return ", ".join(entry.skills)
