"""Tests for reinicorn.skillset.wiring."""

from __future__ import annotations

from pathlib import Path
from unittest.mock import patch as mock_patch

import pytest

from reinicorn.doc_types import REGISTRY, Addressing, DocType
from reinicorn.skillset.adapter import AdapterError, WiringEntry
from reinicorn.skillset.wiring import render_wiring, write_wiring

PHANTOM = DocType(
    key="phantom", dir_path="phantoms", filename="{slug}.md",
    protected=True,
    help_text="Phantom doc operations",
    template_body="\n## Body\n\n_Text._\n",
    addressing=Addressing.SLUG,
)

_HEADER = (
    "# Skillset Wiring\n"
    "\n"
    "Generated by rcorn — do not edit. Regenerated by `rcorn update` and "
    "`rcorn skills`.\n"
    "\n"
    "| Doc type | Create with | Invoke first |\n"
    "|---|---|---|\n"
)


def test_render_wiring_none_lists_every_registry_key_unwired() -> None:
    markdown, skipped = render_wiring(None)
    assert skipped == []
    assert markdown.startswith(_HEADER)
    for dt in REGISTRY.values():
        assert f"| {dt.key} | " in markdown
    # Every row is unwired.
    for line in markdown.splitlines()[6:]:
        assert line.endswith("| — |")


def test_render_wiring_fills_skills_column_from_wiring_entry() -> None:
    wiring = {"spec": WiringEntry(skills=("brainstorming",))}
    markdown, skipped = render_wiring(wiring)
    assert skipped == []
    assert '| spec | `rcorn spec create "<title>"` | brainstorming |' in markdown


def test_render_wiring_joins_multiple_skills_comma_space() -> None:
    wiring = {"plan": WiringEntry(skills=("writing-plans", "executing-plans"))}
    markdown, _skipped = render_wiring(wiring)
    assert (
        "| plan | `rcorn plan create` | writing-plans, executing-plans |"
        in markdown
    )


def test_render_wiring_free_text_create_command() -> None:
    markdown, _skipped = render_wiring(None)
    assert '| idea | `rcorn idea create "<text>"` | — |' in markdown


def test_render_wiring_matches_brief_rendered_shape_exactly() -> None:
    wiring = {
        "spec": WiringEntry(skills=("brainstorming",)),
        "plan": WiringEntry(skills=("writing-plans", "executing-plans")),
    }
    markdown, _skipped = render_wiring(wiring)
    lines = markdown.splitlines()
    assert lines[0] == "# Skillset Wiring"
    assert lines[1] == ""
    assert lines[2] == (
        "Generated by rcorn — do not edit. Regenerated by `rcorn update` "
        "and `rcorn skills`."
    )
    assert lines[3] == ""
    assert lines[4] == "| Doc type | Create with | Invoke first |"
    assert lines[5] == "|---|---|---|"
    assert lines[6] == '| spec | `rcorn spec create "<title>"` | brainstorming |'
    plan_idx = 6 + list(REGISTRY).index("plan")
    assert lines[plan_idx] == (
        "| plan | `rcorn plan create` | writing-plans, executing-plans |"
    )


def test_render_wiring_row_order_is_registry_insertion_order() -> None:
    markdown, _skipped = render_wiring(None)
    lines = [line for line in markdown.splitlines()[6:] if line.strip()]
    keys_in_doc = [line.split("|")[1].strip() for line in lines]
    assert keys_in_doc == list(REGISTRY)


def test_render_wiring_phantom_type_gets_row_with_no_wiring() -> None:
    with mock_patch.dict(REGISTRY, {"phantom": PHANTOM}):
        markdown, skipped = render_wiring(None)
    assert skipped == []
    assert '| phantom | `rcorn phantom create "<title>"` | — |' in markdown


def test_render_wiring_unknown_non_optional_key_raises() -> None:
    wiring = {"bogus": WiringEntry(skills=("alpha",))}
    with pytest.raises(AdapterError) as exc_info:
        render_wiring(wiring)
    message = str(exc_info.value)
    assert "bogus" in message
    assert str(sorted(REGISTRY)) in message


def test_render_wiring_unknown_optional_key_is_skipped() -> None:
    wiring = {
        "bogus": WiringEntry(skills=("alpha",), optional=True),
        "spec": WiringEntry(skills=("brainstorming",)),
    }
    markdown, skipped = render_wiring(wiring)
    assert skipped == ["bogus"]
    assert "bogus" not in markdown
    assert '| spec | `rcorn spec create "<title>"` | brainstorming |' in markdown


def test_write_wiring_creates_parent_dirs_and_returns_path(tmp_path: Path) -> None:
    path = write_wiring(tmp_path, None)
    assert path == (
        tmp_path
        / ".agents"
        / "skills"
        / "using-reinicorn"
        / "references"
        / "skillset-wiring.md"
    )
    assert path.is_file()
    assert path.read_text().startswith("# Skillset Wiring\n")


def test_write_wiring_respects_configured_skills_dir(tmp_path: Path) -> None:
    (tmp_path / ".reinicorn-config").write_text("REINICORN_SKILLS_DIR=custom/skills\n")
    path = write_wiring(tmp_path, None)
    assert path == (
        tmp_path
        / "custom"
        / "skills"
        / "using-reinicorn"
        / "references"
        / "skillset-wiring.md"
    )
    assert path.is_file()
